# Generated by Django 3.0.3 on 2021-04-08 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date_for',
            field=models.DateField(),
        ),
    ]
